apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-deployment
  namespace: homework
  labels:
    app: kubernetes-controllers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      serviceAccountName: monitoring
      containers:
        - name: nginx
          image: nginx:1.28.0-alpine
          ports:
            - containerPort: 8000
              name: nginx-port
          readinessProbe:
            httpGet:
              path: /index.html
              port: nginx-port
            initialDelaySeconds: 5
            failureThreshold: 5
            periodSeconds: 5
          volumeMounts:
            - name: workdir
              mountPath: "/homework"
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
              readOnly: true
            - name: vol-configmap
              mountPath: /homework/conf
              readOnly: true
          lifecycle:
            preStop:
              exec:
                command:
                  - rm
                  - -f
                  - /homework/index.html
      initContainers:
        - name: init-container
          image: busybox:1.37
          command:
            - wget
            - "-O"
            - "/init/index.html"
            - http://info.cern.ch
          volumeMounts:
            - name: workdir
              mountPath: "/init"
      volumes:
        - name: workdir
          persistentVolumeClaim:
            claimName: kubernetes-pvc
        - name: nginx-config
          configMap:
            name: nginx-configmap
        - name: vol-configmap
          configMap:
            name: kubernetes-configmap
      nodeSelector:
        homework: "true"

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
