apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: homework
data:
  server.conf: |
    server {
      listen       8000;
      listen  [::]:8000;
      server_name  _;
      access_log  /var/log/nginx/server.access.log  main;
      location / {
        root   /homework;
        index  index.html index.htm;
      }
    }
