apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetes-pvc
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: nginx-pod
